spring:
   application:
      name: 'fornecedor'
   datasource:
      password: bp2507a
      username: admin
      url: jdbc:mysql://localhost:3306/lojas
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
      properties:
         format_sql: true
